stages:
  - build
  - deploy
  - publish
cache:
  untracked: true
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - _site/vendor/
    - .bundled/
    - .yarn

before_script:
  - mkdir -p ~/.ssh
  - touch ~/.ssh/id_rsa
  - touch ~/.ssh/config
  - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
  - chmod 700 ~/.ssh/id_rsa
  - echo "$SSH_CONFIG" > ~/.ssh/config

build_prod:
  stage: build
  environment:
    name: prod
  only:
    - master
  script:
    - echo "$ENV" > .env
    - yarn config set registry "https://registry.npm.taobao.org"
    - yarn
    - yarn build
  artifacts:
    paths:
      - dist

build_test:
  stage: build
  only:
    - test
  environment:
    name: test
  script:
    - echo "$ENV" > .env
    - yarn config set registry "https://registry.npm.taobao.org"
    - yarn
    - yarn build
  artifacts:
    paths:
      - dist

deploy to test:
  image: instrumentisto/rsync-ssh
  environment:
    name: test
  stage: deploy
  dependencies:
    - build_test
  script:
    - rsync -arzv --delete -e "ssh -i ~/.ssh/id_rsa" dist/ ${HOST}:/mnt/test/authing/guard
  only:
    - test

deploy to pre:
  image: instrumentisto/rsync-ssh
  environment:
    name: pre
  stage: deploy
  dependencies:
    - build_prod
  script:
    - rsync -arzv --delete -e "ssh -i ~/.ssh/id_rsa" dist/ ${HOST}:/mnt/pre/authing/guard
  only:
    - master

deploy to cn:
  image: instrumentisto/rsync-ssh
  stage: deploy
  dependencies:
    - build_prod
  environment:
    name: cn
  script:
    - rsync -arzv --delete -e "ssh -i ~/.ssh/id_rsa" dist/ ${HOST}:/mnt/cn/authing/guard
  when: manual
  only:
    - master

deploy to co:
  image: instrumentisto/rsync-ssh
  stage: deploy
  environment:
    name: co
  script:
    - rsync -arzv --delete -e "ssh -i ~/.ssh/id_rsa" dist/ ${HOST}:/mnt/co/authing/guard
  when: manual
  dependencies:
    - build_prod
  only:
    - master

publish:
  stage: publish
  when: manual
  script:
    - npm run build-pack
    - npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
    - npm publish
  only:
    - master
