stages: 
  - build
  - deploy
cache:
  untracked: true
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - _site/vendor/
    - .bundled/
    - .yarn

before_script:
  - mkdir -p ~/.ssh
  - touch ~/.ssh/id_rsa
  - touch ~/.ssh/config
  - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
  - chmod 700 ~/.ssh/id_rsa
  - echo "$SSH_CONFIG" > ~/.ssh/config
build:
  stage: build
  script:
    - yarn config set registry "https://registry.npm.taobao.org"
    - yarn
    - yarn build 
  artifacts:
    paths:
      - dist

deploy to pre:
  image: instrumentisto/rsync-ssh
  environment: hosts
  stage: deploy
  script: 
    - rsync -arzv --delete -e "ssh -i ~/.ssh/id_rsa" dist/ ${PRE_HOST}:/mnt/pre/authing/guard --rsync-path="sudo rsync"
  only: 
    - master
deploy to prod:
  image: instrumentisto/rsync-ssh
  stage: deploy
  environment: cn
  script: 
    - rsync -arzv --delete -e "ssh -i ~/.ssh/id_rsa" dist/ ${PROD_HOST}:/mnt/authing/guard  --rsync-path="sudo rsync"
  when: manual
deploy to prod:
  image: instrumentisto/rsync-ssh
  stage: deploy
  environment: co
  script: 
    - rsync -arzv --delete -e "ssh -i ~/.ssh/id_rsa" dist/ ${PROD_HOST}:/mnt/authing/guard  --rsync-path="sudo rsync"
  when: manual