stages: 
  - build
  - deploy
  - publish
cache:
  untracked: true
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - _site/vendor/
    - .bundled/
    - .yarn

before_script:
  - mkdir -p ~/.ssh
  - touch ~/.ssh/id_rsa
  - touch ~/.ssh/config
  - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
  - chmod 700 ~/.ssh/id_rsa
  - echo "$SSH_CONFIG" > ~/.ssh/config
build:
  stage: build
  script:
    - yarn config set registry "https://registry.npm.taobao.org"
    - yarn
    - yarn build 
  artifacts:
    paths:
      - dist
deploy to test:
  image: instrumentisto/rsync-ssh
  environment: hosts
  stage: deploy
  script: 
    - rsync -arzv --delete -e "ssh -i ~/.ssh/id_rsa" dist/ ${HOST}:/mnt/test/authing/guard 
  only: 
    - test
deploy to pre:
  image: instrumentisto/rsync-ssh
  environment: hosts
  stage: deploy
  script: 
    - rsync -arzv --delete -e "ssh -i ~/.ssh/id_rsa" dist/ ${HOST}:/mnt/pre/authing/guard 
  only: 
    - master
deploy to cn:
  image: instrumentisto/rsync-ssh
  stage: deploy
  environment: cn
  script: 
    - rsync -arzv --delete -e "ssh -i ~/.ssh/id_rsa" dist/ ${HOST}:/mnt/cn/authing/guard  
  when: manual
deploy to co:
  image: instrumentisto/rsync-ssh
  stage: deploy
  environment: co
  script: 
    - rsync -arzv --delete -e "ssh -i ~/.ssh/id_rsa" dist/ ${HOST}:/mnt/co/authing/guard 
  when: manual
publish:
  stage: publish
  when: manual
  script:
    - npm run build-pack
    - npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
    - npm publish