stages:
  - publish

publish:
  stage: publish
  when: manual
  script:
    - npm run build-pack
    - npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
    - npm publish
  only:
    - master
